export const SET_POKEMONS = "SET_POKEMONS";
export type SET_POKEMONS = typeof SET_POKEMONS;

export const SET_POKEMONS_LOADING = "SET_POKEMONS_LOADING";
export type SET_POKEMONS_LOADING = typeof SET_POKEMONS_LOADING;
